apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: photo-gallery-pipeline
spec:
  resources:
  - name: git
    type: git
  - name: image
    type: image
  tasks:
  - name: build
    taskRef:
      name: photo-gallery-build
    resources:
      inputs:
        - name: git
          resource: git
      outputs:
        - name: image
          resource: image
  - name: deploy
    taskRef:
      name: openshift-client
    runAfter:
      - build
    params:
    - name: ARGS
      value:
        - rollout
        - latest
        - photo-gallery
